FROM ghcr.io/martin-deploy/martin-alpine:0.1.0

LABEL org.opencontainers.image.source https://github.com/martin-deploy/dockerfiles

RUN apk add --no-cache nodejs
RUN apk add --no-cache npm
RUN npm install -g typescript
RUN npm install -g ts-node
RUN delgroup ping
RUN adduser -D -u 999 argocd argocd
